# Site settings
name: 乱七八糟
email: 1029034175@qq.com
author: AllanWei
url: AllanWei0113.github.io
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/AllanWei0113/
#baseurl: "/LessOrMore"
description: Wanna Be ...
meta_description: 危能，个人博客。
motto: I will always miss you like a darling!
banner: Keep Moving！

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: AllanWei0113
highlighter: rouge

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]
      


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
